version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    restart: unless-stopped
    ports:
      - $PTC_SITE_PORT:2368
    environment:
      - url=$PTC_SITE_URL
    volumes:
      - ./:/var/lib/ghost/content
