version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    restart: unless-stopped
    ports:
      - $PTC_SITE_PORT:2368
    environment:
      - NODE_ENV
      - url=$PTC_SITE_URL
      - mail__transport=SMTP
      - mail__options__host=$PTC_EMAIL_SERVER
      - mail__options__port"=$PTC_EMAIL_PORT
      - mail__options__auth__user=$PTC_EMAIL_USER
      - mail__options__auth__pass=$PTC_EMAIL_PASSWORD
      - mail__from=$PTC_EMAIL_FROM
    volumes:
      - ./:/var/lib/ghost/content
